version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: indexer
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d indexer"]
      interval: 3s
      timeout: 3s
      retries: 20

  api:
    build: .
    command: ["bun", "run", "dev"]
    environment:
      DATABASE_URL: postgres://app:app@db:5432/indexer
      PORT: "3000"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbdata:
